spring:
  application:
    name: material
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/garage?useTimezone=true&serverTimezone=UTC
    username: root
    password: Trixrio@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

    show-sql: false

# Flyway Configs
#flyway:
#  url: jdbc:mysql://localhost:3306/
#  schemas: garage
#  user: root
#  password: Trixrio@

server:
  port: 8082

#eureka:
#  instance:
#    hostname: localhost
#    port: 8081
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#  server:
#    wait-time-in-ms-when-sync-empty: 3000