spring:
  application:
    name: zuul

server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

#zuul:
#  routes:
#    product:
#      path: /products/**
#      url: http://localhost:8082/products
#    customer:
#      path: /services/customer/**
#      url: http://localhost:9097/v8/customers/active/all
#    sale:
#      path: /services/sale/**
#      url: http://localhost:9099/v4/sales/last